stages:
- name: test
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: echo "hello"
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: registry.cn-hangzhou.aliyuncs.com
timeout: 60
notification: {}
